---
all:
  hosts:
    control:
      node_ip: 172.22.22.101
    facility:
      node_ip: 172.22.22.141
    master:
      node_ip: 172.22.22.122
    node1:
      node_ip: 172.22.22.131
    node2:
      node_ip: 172.22.22.132
    node3:
      node_ip: 172.22.22.133
